controller_frequency: 5.0

TrajectoryPlannerROS:
  holonomic_robot: false
  publish_cost_grid_pc: true
  pdist_scale: 1.4
  gdist_scale: 0.4
  occdist_scale: 0.05
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_theta: 0.5
  min_vel_theta: -0.5


